### ISSUE TITLE
Error when installing from Chrome Web Store

### ISSUE THREAD

**Issue by rpunkfu** [bfred-it/github-clean-feed#13]
There's error that extension cannot load `option-init.js`, I managed to install it manually and it looks like you published it without building it first :)

**Comment by bfred-it** [comment]
Ouchhh you're right, I didn't add the build step to the [autodeployment](https://github.com/bfred-it/github-clean-feed/commit/5c5e89cd5348504b775d68f9157b0a769778ee5d)

Thanks for opening an issue! 2.1.1 should work

I'm surprised/annoyed that the webstore doesn't automatically check for files on publish, but fails on install instead. 😥
